version: '3.8'
services:
  weather-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - PORT=8080
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: weatherdb
    ports:
      - "5432:5432"
